import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

import { Helmet } from 'react-helmet'
import { Header, Main } from '../components'

const Home: NextPage = () => {  
  const [useShowToggleMenu, setUseShowToggleMenu] = useState<boolean>(false);
  const [search, setSearch] = useState<string>("");
  
  return (
    <div>
      <Head>
        <Helmet>
          <title>Youtube Clone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Helmet>
      </Head>

      <main style={{ height: '100vh', backgroundColor: '#181818' }}>
        {/* HEADER */}
        <Header 
          setSearch={setSearch}
          setShow={setUseShowToggleMenu} 
        />
        {/* INFO */}
        <Main 
          search={search}
          show={useShowToggleMenu} 
        />
      </main>

    </div>
  )
}

export default Home
